//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAssignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesTable
    {
        public int Movie_ID { get; set; }
        public string Movie_Name { get; set; }
        public Nullable<System.DateTime> Movie_DOR { get; set; }
    }
}
