//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPMVCWebAppAssign1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string AccountNumber { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> Balance { get; set; }
    }
}
